"""garbageCollection

Revision ID: 3ecb0c3027d2
Revises: 97aaaf6c6922
Create Date: 2024-05-10 20:28:20.012402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecb0c3027d2'
down_revision: Union[str, None] = '97aaaf6c6922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garbage_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('collection_plan_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('sts_id', sa.Integer(), nullable=True),
    sa.Column('collection_start_time', sa.Integer(), nullable=False),
    sa.Column('collection_end_time', sa.Integer(), nullable=True),
    sa.Column('collected_weight', sa.Float(), nullable=True),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['collection_plan_id'], ['collection_plans.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['sts_id'], ['sts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_garbage_collection_id'), 'garbage_collection', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garbage_collection_id'), table_name='garbage_collection')
    op.drop_table('garbage_collection')
    # ### end Alembic commands ###
