"""add_word_to_plan

Revision ID: 6702c257243a
Revises: d6f2c9afc6dd
Create Date: 2024-05-10 18:49:26.424082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6702c257243a'
down_revision: Union[str, None] = 'd6f2c9afc6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_plans', sa.Column('ward', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_plans', 'ward')
    # ### end Alembic commands ###
