"""contract_manager

Revision ID: a0a19e8df32a
Revises: bbc848f20784
Create Date: 2024-05-10 16:11:10.341821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a19e8df32a'
down_revision: Union[str, None] = 'bbc848f20784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_managers_id'), 'contract_managers', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_reg_id'), 'contracts', ['reg_id'], unique=True)
    op.create_index(op.f('ix_contracts_tin'), 'contracts', ['tin'], unique=True)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'contact')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_contracts_tin'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_reg_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contract_managers_id'), table_name='contract_managers')
    op.drop_table('contract_managers')
    # ### end Alembic commands ###
