"""contract

Revision ID: bbc848f20784
Revises: 6257bc4cd9ab
Create Date: 2024-05-10 15:09:39.384491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc848f20784'
down_revision: Union[str, None] = '6257bc4cd9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('reg_id', sa.String(), nullable=False),
        sa.Column('reg_date', sa.Integer(), nullable=False),
        sa.Column('tin', sa.String(), nullable=False),
        sa.Column('contact', sa.String(), nullable=False),
        sa.Column('workforce_size', sa.Integer(), nullable=False),
        sa.Column('pay_per_ton', sa.Float(), nullable=False),
        sa.Column('required_waste_ton', sa.Float(), nullable=False),
        sa.Column('contract_duration', sa.Integer(), nullable=False),
        sa.Column('area_of_collection', sa.String(), nullable=False),
        sa.Column('sts_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['sts_id'], ['sts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
